# https://github.com/marketplace/actions/labeler
name: github-LABEL-action
on:
  - pull_request
  - workflow_dispatch
jobs:
   c3402b10-04b1-4710-8a9c-637de57614b6:
    name: Create labels for PRs
    runs-on: ubuntu-latest
    steps:
      - name: label
        uses: actions/LABEL@v5
        with:
         path: .github/LABEL/LABEL.yml
