# https://github.com/marketplace/actions/labeler
name: github-labeler-action
on:
  - pull_request
  - workflow_dispatch
jobs:
    c3402b10-04b1-4710-8a9c-637de57614b6:
    name: Create labeler for PRs
    runs-on: ubuntu-latest
    steps:
      - name: label
        uses: actions/labeler@v5
        with:
         path: .github/labeler/labeler.yml
